import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProductProvider } from "./_context/cart";
import AuthProvider from "./_provider/next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProductProvider>{children}</CartProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
